/* eslint-disable import/prefer-default-export */

export const HELLO_WORLD_NAME_UPDATE = 'HELLO_WORLD_NAME_UPDATE';

// Create Movie
export const POST_MOVIE_LOADING = 'POST_MOVIE_LOADING';
export const POST_MOVIE_SUCCESS = 'POST_MOVIE_SUCCESS';
export const POST_MOVIE_FAILURE = 'POST_MOVIE_FAILURE';

// Get A Movie
export const GET_MOVIE_LOADING = 'GET_MOVIE_LOADING';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILURE = 'GET_MOVIE_FAILURE';

// Get All Movies
export const GET_ALL_MOVIE_LOADING = 'GET_ALL_MOVIE_LOADING';
export const GET_ALL_MOVIE_SUCCESS = 'GET_ALL_MOVIE_SUCCESS';
export const GET_ALL_MOVIE_FAILURE = 'GET_ALL_MOVIE_FAILURE';

// Update Movie
export const UPDATE_MOVIE_LOADING = 'UPDATE_MOVIE_LOADING';
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS';
export const UPDATE_MOVIE_FAILURE = 'UPDATE_MOVIE_FAILURE';

// Delete Movie
export const DELETE_MOVIE_LOADING = 'DELETE_MOVIE_LOADING';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE';
